heat_template_version: 2017-02-24
description: Kubernetes node definition
parameters:
    index:
        type: number
        label: Index
        description: Index in floating IP list
    key_name:
        type: string
        label: Key Name
        description: SSH key to be used for all instances
    image:
        type: string
        label: Image
        description: Image to be used
    flavor:
        type: string
        label: Instance Type
        description: Type of instance (flavor) to deploy node
    public_network_id:
        type: string
        description: ID of the public network
        default: public
    availability_zone:
        type: string
        label: Availability Zone
        description: Availabilito zone to create nodes in
    name:
        type: string
        label: Instance Name
        description: Name of the node
    internal_net:
        type: string
        label: Internal Network
        description: Network to connect node to
    install_script:
        type: string
        label: Install Script
        description: Script to run after cloud-init finishes
    additional_config:
        type: string
        label: Additional Config
        description: Additional software config
        default: ""
    security_group:
        type: string
        label: Security Group
        description: Security group to apply to nodes
    proxy_host:
        type: string
        label: Proxy Host
        description: Proxy host to use
        default: ""
    proxy_port:
        type: number
        label: Proxy Port
        description: Proxy port to use
        default: 0
    volume_size:
        type: number
        default: 50
   
conditions:
    empty_additional_config:
        equals:
            - { get_param: additional_config }
            - ""
    empty_proxy:
        equals:
            - { get_param: proxy_host }
            - ""
resources:
    port:
        type: OS::Neutron::Port
        properties:
            admin_state_up: true
            network_id: { get_param: internal_net }
            security_groups:
                - { get_param: security_group }
    instance_floatingip:
        type: OS::Neutron::FloatingIP
        properties:
            floating_network_id: { get_param: public_network_id }
            port_id: { get_resource: port }
    instance:
        type: OS::Nova::Server
        properties:
            availability_zone: { get_param: availability_zone }
            flavor: { get_param: flavor }
            key_name: { get_param: key_name }
            networks:
                - port: { get_resource: port }
            name: { get_param: name }
            user_data_format: SOFTWARE_CONFIG
            user_data: { get_resource: user_data }
            block_device_mapping_v2:
                - device_name: vda
                  image: { get_param: image }
                  volume_size: { get_param: volume_size }
                  delete_on_termination: True
    user_data_base:
        type: OS::Heat::CloudConfig
        properties:
            cloud_config:
                #cloud-config
                manage_etc_hosts: localhost
                package_update: true
                packages:
                    - socat
                runcmd:
                    - - 'systemd-run'
                      - '--on-boot=0s'
                      - '--unit=kubeadm-install'
                      - 'bash'
                      - '-c'
                      - { get_param: install_script }
    user_data_proxy:
        type: OS::Heat::CloudConfig
        properties:
            cloud_config:
                if:
                    - empty_proxy
                    - {}
                    - apt_proxy:
                        str_replace:
                          template: http://$ip:$port
                          params:
                              $ip: { get_param: proxy_host }
                              $port: { get_param: proxy_port }
    user_data:
        type: OS::Heat::MultipartMime
        properties:
            parts:
                if: 
                    - empty_additional_config
                    - - config: { get_resource: user_data_base }
                      - config: { get_resource: user_data_proxy }
                    - - config: { get_resource: user_data_base }
                      - config: { get_resource: user_data_proxy }
                      - config: { get_param: additional_config }
outputs:
  ip:
    description: Master IP of kubernetes cluster
    value: {get_attr: [ instance_floatingip, floating_ip_address] }
