heat_template_version: 2017-02-24
description: Deploy Kubernetes cluster with kubeadm

parameters:
    key_name:
        type: string
        label: Key Name
        description: SSH key to be used for all instances
    image:
        type: string
        label: Image
        description: Image to be used
        default: ubuntu-16-04-amd64-cloudimg    
    master_flavor:
        type: string
        label: Master Instance Type
        description: Type of instance (flavor) to deploy master node
        default: m1.small
    slave_count:
        type: number
        label: Slave Count
        description: Number of slaves
        default: 3
    slave_flavor:
        type: string
        label: Slave Instance Type
        description: Type of instance (flavor) to deploy slave nodes
        default: m1.small
    public_network_id:
        type: string
        description: ID of the public network
        default: public
    resource_prefix:
        type: string
        description: Prefix to add to all resources
        default: k8s-
    dns_nameservers:
        type: comma_delimited_list
        label: DNS Nameservers
        description: DNS nameservers to use on nodes
        default: 8.8.8.8
    availability_zone:
        type: string
        label: Availability Zone
        description: Availabilito zone to create nodes in
    proxy_host:
        type: string
        label: Proxy Host
        description: Proxy host to use
        default: ""
    proxy_port:
        type: number
        label: Proxy Port
        description: Proxy port to use
        default: 0
    volume_size:
        type: number
        default: 50

conditions:
    deploy_proxy:
        equals:
            - { get_param: proxy_host }
            - "deploy"
resources:
    random_string:
        type: OS::Heat::RandomString
        properties:
            length: 8
            sequence: lowercase
    prefix_random:
        type: OS::Heat::Value
        properties:
            value:
                str_replace:
                    template: $prefix$random
                    params:
                        $prefix: { get_param: resource_prefix }
                        $random: { get_resource: random_string }

    ##### Network #####
    internal_net:
        type: OS::Neutron::Net
        properties:
            admin_state_up: true
            name:
                str_replace:
                    template: $prefix-network
                    params:
                        $prefix: { get_attr: [prefix_random, value] }
    internal_subnet:
        type: OS::Neutron::Subnet
        properties:
            network_id: { get_resource: internal_net }
            cidr: 10.2.2.0/24
            gateway_ip: 10.2.2.1
            enable_dhcp: true
            dns_nameservers: { get_param: dns_nameservers }
            name:
                str_replace:
                    template: $prefix-subnet
                    params:
                        $prefix: { get_attr: [prefix_random, value] }
    internal_router:
        type: OS::Neutron::Router
        properties:
            admin_state_up: true
            external_gateway_info: { "network": { get_param: public_network_id }}
            name:
                str_replace:
                    template: $prefix-router
                    params:
                        $prefix: { get_attr: [prefix_random, value] }
    internal_router_interface:
        type: OS::Neutron::RouterInterface
        properties:
            router_id: { get_resource: internal_router }
            subnet_id: { get_resource: internal_subnet }
    security_group:
        type: OS::Neutron::SecurityGroup
        properties:
            name:
                str_replace:
                    template: $prefix-security-group
                    params:
                        $prefix: { get_attr: [prefix_random, value] }
            rules:
                - remote_mode: remote_group_id
                  direction: ingress
                - remote_mode: remote_group_id
                  direction: egress
                - direction: egress
                - protocol: icmp
                - port_range_min: 22
                  port_range_max: 22
                  protocol: tcp
                - port_range_min: 6443
                  port_range_max: 6443
                  protocol: tcp
                - port_range_min: 30000
                  port_range_max: 32767
                  protocol: tcp

    ##### Stack #####
    stack:
        type: stack.yaml
        depends_on: internal_subnet
        properties:
            key_name: { get_param: key_name }
            image: { get_param: image }
            master_flavor: { get_param: master_flavor }
            slave_count: { get_param: slave_count }
            slave_flavor: { get_param: slave_flavor }
            public_network_id: { get_param: public_network_id }
            internal_net: { get_resource: internal_net }
            resource_prefix: { get_attr: [prefix_random, value] }
            dns_nameservers: { get_param: dns_nameservers }
            availability_zone: { get_param: availability_zone }
            security_group: { get_resource: security_group }
            volume_size: { get_param: volume_size }
            proxy_host:
                if:
                    - deploy_proxy
                    - { get_attr: [proxy_node, ip_address] }
                    - { get_param: proxy_host }
            proxy_port:
                if:
                    - deploy_proxy
                    - 3128
                    - { get_param: proxy_port }
    proxy_node:
        type: proxy.yaml
        depends_on: internal_subnet
        condition: deploy_proxy
        properties:
            key_name: { get_param: key_name }
            image: { get_param: image }
            flavor: { get_param: master_flavor }
            public_network_id: { get_param: public_network_id }
            internal_net: { get_resource: internal_net }
            resource_prefix: { get_attr: [prefix_random, value] }
            availability_zone: { get_param: availability_zone }
            security_group: { get_resource: security_group }

outputs:
  ip:
    description: Master IP of kubernetes cluster
    value: {get_attr: [stack, ip]}
