heat_template_version: 2017-02-24
description: >
  This template to test volume creation
resources:
   volume:
      type: OS::Cinder::Volume
      properties:
          availability_zone: JMNG-PE3-NONPROD
          image: Ubuntu1604
          name: testing
          size: 10
          volume_type: ceph 
outputs:
  volume_info: 
    description: volume details
    value:
      str_replace:
        template: $host1
        params:
          $host1: { get_attr: [volume] }

    
